version: '3'

networks:
    laravel-network: 
       driver: bridge

services:
    nginx: 
      image: 'nginx:stable-alpine'
      container_name: 'nginx_laravel'
     
      ports: 
        - "80:80"
      volumes: 
        - './src:/var/www/html'
        - './nginx-default.conf:/etc/nginx/conf.d'
      depends_on:
        - php
        - mysql
      networks:
        - laravel-network
    mysql:
      image: "mysql:8.0"
      container_name: 'mysql_laravel'
      ports: 
        - '3307:3306'
      networks:
        - laravel-network
      environment:
        - MYSQL_ROOT_PASSWORD=dominic1234"
        - MYSQL_DATABSE=dockers
        - MYSQL_USER=dominic
        - MYSQL_PASSWORD=dominic1234 

    php: 
      build:
        dockerfile: Dockerfile
        context: . 
      container_name: 'php_laravel'
      ports: 
        - '9000:9000'
      volumes: 
        - './src:/var/www/html'
        - './nginx.conf:/etc/nginx/conf.d/default.conf'
      networks: 
        - laravel-network

    composer: 
      image: 'composer:latest'
      container_name: 'composer_laravel'
      volumes: 
        - './src:/var/www/html'
      working_dir: /var/www/html
      networks: 
        - laravel-network

    npm: 
      image: 'node:13.7'
      container_name: 'npm_laravel'
      volumes: 
        - './src:/var/www/html'
      working_dir: /var/www/html
      networks: 
        - laravel-network
      entrypoint:
        - npm
